### ISSUE TITLE
User email address not saved in db

### ISSUE THREAD

**Issue by naazy** [facstars/finding-nemo#248]

**Comment by Jbarget** [comment]
@naazy can you explain when this is happening or whats causing it?

**Comment by naazy** [comment]
@Jbarget i think we must just not be saving the email addresses? try creating a user account and typing in an email address and then look in the db? i tried it on friday and i coluldn't see the email address saved but maybe i'm imagining? obv a v easy fix :)

**Comment by Jbarget** [comment]
Oh yeh i forgot we were never actually doing anything with the email address. 
what do we want to be doing?

**Comment by naazy** [comment]
we dont do anything with the db but i think it's important to save it cos the girls want the data @Jbarget  (otherwise there' be no point in even asking them for it)

**Comment by Jbarget** [comment]
for the restaurants? i can add it to each individual restaurant, just give me the go ahead

**Comment by naazy** [comment]
this is because there is no input for email addresses!
