### ISSUE TITLE
User side does not work in private browsing

### ISSUE THREAD

**Issue by naazy** [facstars/finding-nemo#250]
Try accessing auth.uid instead?

**Comment by naazy** [comment]
https://gist.github.com/philfreo/68ea3cd980d72383c951

**Comment by Jbarget** [comment]
@naazy can you explain whats not actually working

**Comment by naazy** [comment]
@Jbarget position number in the queue etc not working. this is because uid is saved in local storage when the user logs in (but it's not possible to set something in local storage when a user logs in using private browsing). the founders didn't mention this bug but i spotted it. quite easily fixable tho . i think we just need to access auth.uid

**Comment by naazy** [comment]
alternatively - we could write a function that checks if a user is in private browsing and if they are then we could store the uid in the url e.g. '/user/restlist/uid123' @Jbarget

**Comment by naazy** [comment]
@Jbarget  we'll probably have the same prob with the rest side too cos RUID is stored in local storage when a rest logs in

**Comment by Jbarget** [comment]
i havent been able to recreate this bug

**Comment by naazy** [comment]
@Jbarget i just spotted it when afroditi loggged in for the first time at fac. and then i made her go off private browsing and it was fine... have u tried with rest side too?

**Comment by Jbarget** [comment]
yep
do you want to double check?

**Comment by naazy** [comment]
i think this is fine...
