### ISSUE TITLE
Change some text 

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#262]
Can you write "Can’t seat" instead of "cannot seat"
Can you change the text messages to:
Table ready: Hello! Your table will be ready shortly. Please head to the restaurant. Enjoy your meal. Cheers, SkipIt!
Table Cancelled: Hello! We are really sorry but the restaurant had to cancel your booking. Feel free to checkout other amazing restaurants near you. SkipIt!

**Comment by Jbarget** [comment]
fixed with 32d7c5996a248b536c9afe12a4ac3158cca3fdc9
