### ISSUE TITLE
After creating account can't log in 

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#264]
"When Afroditi tried to create an account she couldn’t login at all. She tried different numbers and names and nothing worked."

**Comment by katkelemen** [comment]
not sure this is still a problem?

**Comment by naazy** [comment]
this now seems to be working. i think @Jbarget fixed?

**Comment by Jbarget** [comment]
im not sure if i did

**Comment by Jbarget** [comment]
did anyone recreate the bug?
