### ISSUE TITLE
the page looks is not refreshing so you are unsure if the message “invalid phone number or password” is from your previous mistake or this one.

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#265]
"Also, the page looks like it's not refreshing so you are unsure if the message “invalid phone number or password” is from your previous mistake or this one."

**Comment by katkelemen** [comment]
the input fields are cleared so i think its obvious that the latest phone number or pw is incorrect.
what do you think?

**Comment by naazy** [comment]
maybe when u click on the input, it should clear that message?

**Comment by naazy** [comment]
im happy to do this - will do it now quickly

**Comment by Jbarget** [comment]
"wontfix"?

@naazy arent you fixing this one?

**Comment by naazy** [comment]
yeah i've just cleared the message when they click the input box .about to commit @katkelemen @Jbarget
