### ISSUE TITLE
Basically when something does’t fit you can’t scroll down to see it!

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#269]
"On our  android and iPhones, when trying to check in at another restaurants, I can’t scroll down and see the message “You can’t queue at more than one restaurant” and I can’t scroll down to leave the queue on the other restaurant either. On the restaurant interface its the same, basically when something does’t fit you can’t scroll down to see it!"

**Comment by Jbarget** [comment]
@katkelemen did you work on this yesterday/ is it done?

**Comment by katkelemen** [comment]
@i think yes im closing this :)
