### ISSUE TITLE
I removed a restaurant I was queuing at and now my user account is blocked because it didn’t delete my ticket. 

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#270]

**Comment by naazy** [comment]
@Jbarget @katkelemen  i'm confused about why this would/could happen? surely when a restaurant is deleted, then it clears the waitlist?

**Comment by naazy** [comment]
AHH i know why! it's because when a restaurant is removed, it also needs to change the details in the user db e.g. 'already on waitlist' and 'queueRUID'

**Comment by Jbarget** [comment]
yeh, which is quite tricky

**Comment by naazy** [comment]
mmm - i guess we'll have to check each user's 'queueRuid' to see if it matches the Ruid of the rest we wana remove

**Comment by Jbarget** [comment]
or we could change it so that we dont actually need "alreadyOnWaitlist" and just check to see if queueRuid isnt null, then we can do it all in one request i think.

**Comment by Jbarget** [comment]
cos if theres a queueRuid then the user will already be on a waiting list

**Comment by Jbarget** [comment]
@naazy whatcha thinking for this?

**Comment by naazy** [comment]
@Jbarget just doing this now :)
