### ISSUE TITLE
Also, is it possible to make all the guest list fit (ref screenshot)

### ISSUE THREAD

**Issue by katkelemen** [facstars/finding-nemo#271]
![unnamed 1](https://cloud.githubusercontent.com/assets/9272148/12919776/90531e28-cf3d-11e5-9898-f9f6555250cc.jpg)

**Comment by naazy** [comment]
do you tihnnk they mean put the buttons all on the same line? e.g. cannot seat and table ready?

**Comment by Jbarget** [comment]
yep
i'll do this today
