### ISSUE TITLE
Pictures are squashed on iPad (portrait) screen 

### ISSUE THREAD

**Issue by Jbarget** [facstars/finding-nemo#280]
![screen shot 2016-02-10 at 11 39 34](https://cloud.githubusercontent.com/assets/11725595/12946276/0fc35d78-cfeb-11e5-9479-779526d6c074.png)

**Comment by naazy** [comment]
they're not squashed on my iphone5? @Jbarget

**Comment by Jbarget** [comment]
hmmm, this was in the dev tools, ill look on mine

**Comment by Jbarget** [comment]
Ohhhh its on an iPad (portrait)
