### ISSUE TITLE
realign checking box on restSpecific.html

### ISSUE THREAD

**Issue by Jbarget** [facstars/finding-nemo#282]
![screen shot 2016-02-10 at 16 56 15](https://cloud.githubusercontent.com/assets/11725595/12954624/44aeffc0-d017-11e5-859b-2934c550c4e7.png)

**Comment by naazy** [comment]
is this on an ipad? @Jbarget

**Comment by Jbarget** [comment]
@naazy on ipad (landscape & portrait) & browser

**Comment by Jbarget** [comment]
fixed with 1a90a44
