### ISSUE TITLE
FE: populate restSpecific.html with info from #38

### ISSUE THREAD

**Issue by Jbarget** [facstars/finding-nemo#41]
#38

**Comment by naazy** [comment]
still needs doing for phone no and no of guests

**Comment by naazy** [comment]
store no of guests here:

https://blistering-torch-1660.firebaseio.com/restaurants/bae9759f-03e1-440f-937e-8a1fb9e4a23d/waitlist/table2/guests /no of guests e.g.2

and retrieve phone number from user db
