### ISSUE TITLE
BE: send text to user when 'get ready' button is clicked

### ISSUE THREAD

**Issue by Jbarget** [facstars/finding-nemo#42]

**Comment by Jbarget** [comment]
https://twilio.github.io/twilio-node/

**Comment by Jbarget** [comment]
https://www.twilio.com/

**Comment by naazy** [comment]
https://www.messagebird.com/app/en-gb/user/index

**Comment by naazy** [comment]
http://blog.messagebird.com/2015/12/easy-sms-integration-node-js/
