### ISSUE TITLE
Auth for user side using firebase custom login 

### ISSUE THREAD

**Issue by naazy** [facstars/finding-nemo#66]

**Comment by naazy** [comment]
uid should be saved here: https://blistering-torch-1660.firebaseio.com/users

**Comment by katkelemen** [comment]
To use the firebase secret for creating secure tokens in development you must set up an environment variable called FIREBASE_SECRET like so:

```
export FIREBASE_SECRET="ybXX....<get the rest of it from firebase admin>"
npm start
```

you only have to export it once per terminal window, as in you can start and restart your node server many times without exporting the token

to check if you have the token set see your env by using the `env` command

**Comment by naazy** [comment]
@katkelemen  i think we can just save the secret in our config.env file? will give it a go now

**Comment by naazy** [comment]
yes - it now works. you needed to put this user in userlogin.js:
var env = require('env2')('config.env');

and then

FIREBASE_SECRET=ybXXkGCcoZPy4URZYY87gAeo8vk5Hrhop5Ry2Tuq

in your config.env
